# Generated by Django 6.0.1 on 2026-01-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='product',
        ),
        migrations.AddField(
            model_name='demand',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demand',
            name='name',
            field=models.CharField(default='Unknown Product', max_length=100),
            preserve_default=False,
        ),
    ]
