# Generated by Django 6.0.1 on 2026-01-15 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0002_remove_demand_product_demand_comment_demand_name'),
        ('products', '0002_product_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='name',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='quantity',
        ),
        migrations.CreateModel(
            name='DemandItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='demands.demand')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
