# Generated by Django 6.0.1 on 2026-01-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0003_remove_demand_name_remove_demand_quantity_demanditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='demander_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
