# Generated by Django 6.0.1 on 2026-01-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0004_demand_demander_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='demand',
            name='email_to',
            field=models.EmailField(default='Unknown', max_length=254, verbose_name='Email to send demand'),
            preserve_default=False,
        ),
    ]
