# Generated by Django 6.0.1 on 2026-01-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_stockmovement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockmovement',
            old_name='created_at',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
