# Generated by Django 6.0.1 on 2026-01-19 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_created_at_stockmovement_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockMovement',
        ),
    ]
